baseURL: "https://parkinjong.github.io/github.io-test/"
title: InJongPark
languageCode: kr-ko
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "linkedin"
      url: "https://www.linkedin.com/in/injong-park-535bb5235/"
    - name: "github"
      url: "https://github.com/parkinjong"
    - name: "kakaotalk"
      url: "https://open.kakao.com/o/sK20qg8e"
  # profileMode:
  #   enabled: true
  #   title: "InJong Park" # optional default will be site title
  #   subtitle: "IT는 어려워요"
  #   # imageUrl: "<image link>" # optional
  #   # imageTitle: "<title of image as alt>" # optional
  #   imageWidth: 120 # custom size
  #   imageHeight: 120 # custom size
  #   # buttons:
  #   #   - name: Archive
  #   #   url: "/archives"
  #   #   - name: Github
  #   #   url: "https://github.com/parkinjong"
  #   # socialIcons: # optional
  #   #     - name: "<platform>"
  #   #         url: "<link>"
  #   #     - name: "<platform 2>"
  #   #         url: "<link2>"
  ShowBreadCrumbs: true
  # ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true
  
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary